services:
  - type: web
    name: chat-hub
    env: python
    buildCommand: ""
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    plan: free
    envVars:
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: EMAIL_ADDRESS
        value: ${EMAIL_ADDRESS}
      - key: EMAIL_PASSWORD
        value: ${EMAIL_PASSWORD}
      - key: MONGO_URI
        value: ${MONGO_URI}